export default [
	"Datawrapper",
	"Frontend Masters",
	"Dabble",
	"Vercel",
	"Avast",
	"Hugging Face",
	"Layer0",
	"Matt",
	"Kenoxa GmbH",
	"PQINA",
	"The Pudding",
	"Zev Averbach",
	"Donovan Dikaio",
	"INVISR",
	"Jason Hetherington",
	"Threema Open Source Fund",
	"Jailbreak",
	"Dong-won Jeffrey Lee",
	"Level Up Tutorials",
	"BuildLab",
	"David Stevens",
	"Emma Agering",
	"Morgan Williams",
	"Johan Ronsse"
];